### ISSUE TITLE
Ava- Week 17 Progress and To-Do

### ISSUE THREAD

**Issue by avac54765** [SRIHITAKOTT1213/FamReunion#3]
Ava:

- [ ] edit _config.yml (title, link, theme, description)
- [ ] edit theme, sass, CSS (SASS, _assets/css/style.css and CSS customization within style.css)
- [ ] research sass and CSS (watch videos)
- [ ] Agile Manifesto
- [ ] make sports page with Lydia
- [ ] customize _layouts/default.html
- [x]  Jekyll build (local host)
- [ ] edit image layouts (SASS, _assets/css/style.css and CSS customization within style.css)
