### ISSUE TITLE
Week 17 Sri Progress/To-Do-List

### ISSUE THREAD

**Issue by SRIHITAKOTT1213** [SRIHITAKOTT1213/FamReunion#5]
- [x] Create a local host
- [x] Change the names of the table
- [x] figure out how to make changes without messing things up
- [ ] Find out how I want to present the workout logs
- [ ] Try coding an add button for tables so that anyone can add a new column
